POST https://asia-northeast1-superfarmers.cloudfunctions.net/Insert
Content-Type: application/json

{
  "uuid": "test",
  "liquid_temperature": 30,
  "temperature": 28,
  "humidity": 60,
  "liquid_flow_rate": 0.3,
  "ph": 6.7,
  "ec": 1.11,
  "light": 42,
  "liquid_level": true,
  "valve": false,
  "led": true,
  "fan": false
}

###

POST https://asia-northeast1-superfarmers.cloudfunctions.net/Insert
Content-Type: application/json

{
  "uuid": "test",
  "liquid_temperature": 30,
  "temperature": 28,
  "humidity": 60,
  "liquid_flow_rate": 0.3,
  "ph": 15,
  "ec": 1.11,
  "light": 42,
  "liquid_level": false,
  "valve": false,
  "led": false,
  "fan": false
}